### ISSUE TITLE
RC4 algorithm implementation in C

### ISSUE THREAD

**Issue by 0xwal** [0xWaleed/c-scratch#3]
# RC4 Encryption

### Description:
Write the RC4 algorithm to encrypt/decrypt data.

#### Header:

`src/include/rc4.h`

#### Source file:

`src/rc4.c`

#### Test file:

`tests/rc4.test.cpp`

#### Signature:

```c
void rc4(const char* key, size_t keyLength, const char* plain, size_t plainLength, char* result);
```

#### Test Cases:
1. Input: `key: "h"` `plain: "foo"`, output: `result: "\xc7\x22\xc7"`
2. Input: `key: "secret"` `plain: "foo"`, output: `result: "\x8b\x59\xbd"`

### Restriction:

* Do not use any builtin string functions.
* Only allowed to use memory functions ex: `malloc`, `calloc`, etc.

### Note:
See [Contribution Guide](https://github.com/0xWaleed/c-scratch/blob/master/CONTRIBUTING.md) for more details.

Let me know if you are unable to write the tests, I will do that for you.

Also if you want any help let me know 😉.

**Comment by 0xWaleed** [comment]
Done 🚀
